# 网站基本信息
title: Runyu Lu - hi
email: lurunyu17@mails.ucas.ac.com
description: >-
  Ph.D. Candidate specializing in Game Theory and Reinforcement Learning at the University of Chinese Academy of Sciences (UCAS).

# 导航栏设置
header_pages:
  - about.md
  - projects.md
  - contact.md

theme: minima
